// <auto-generated />
using EY.HRPlatform.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EY.HRPlatform.Identity.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppIdentityDbContext))]
[Migration("20260621120000_AddOrganizationalAccessScopes")]
partial class AddOrganizationalAccessScopes
{
}
