using EY.HRPlatform.Performance.Domain.Enums;
using EY.HRPlatform.Performance.Exceptions;
using EY.HRPlatform.SharedKernel.Domain;
using EY.HRPlatform.SharedKernel.Multitenancy;

namespace EY.HRPlatform.Performance.Domain.Entities;

/// <summary>
/// A frozen participant-to-assignee relationship generated by one round launch.
/// Assessment authoring transitions are reserved for the following capability.
/// </summary>
public sealed class EvaluationAssignment : AggregateRoot, ITenantEntity
{
    private EvaluationAssignment() { }

    public Guid TenantId { get; private set; }
    public Guid RoundId { get; private set; }
    public Guid RoundParticipantId { get; private set; }
    public Guid ParticipantEmployeeId { get; private set; }
    public string ParticipantName { get; private set; } = string.Empty;
    public EvaluationAssignmentKind Kind { get; private set; }
    public Guid AssigneeEmployeeId { get; private set; }
    public string AssigneeName { get; private set; } = string.Empty;
    public Guid ScaleSnapshotId { get; private set; }
    public Guid TemplateSnapshotId { get; private set; }
    public Guid? ObjectivePlanSnapshotId { get; private set; }
    public EvaluationAssignmentStatus Status { get; private set; }
    public uint Version { get; private set; }

    internal static IReadOnlyList<EvaluationAssignment> Generate(
        EvaluationRound round,
        IReadOnlyCollection<EvaluationRoundParticipant> participants)
    {
        if (round.Status != EvaluationRoundStatus.Launched ||
            round.ScaleSnapshot is null ||
            round.TemplateSnapshot is null)
        {
            throw new DomainRuleViolationException("Assignments can only be generated from a launched round snapshot.");
        }

        var assignments = new List<EvaluationAssignment>(
            participants.Count * (round.AssessmentModel == EvaluationAssessmentModel.SelfAndManager ? 2 : 1));

        foreach (var participant in participants)
        {
            if (participant.RoundId != round.Id || participant.TenantId != round.TenantId)
                throw new DomainRuleViolationException("Assignment participants must belong to the launched round.");

            if (round.AssessmentModel == EvaluationAssessmentModel.SelfAndManager)
            {
                assignments.Add(Create(
                    round,
                    participant,
                    EvaluationAssignmentKind.SelfAssessment,
                    participant.EmployeeId,
                    participant.FullName));
            }

            assignments.Add(Create(
                round,
                participant,
                EvaluationAssignmentKind.ManagerAssessment,
                participant.ReviewerEmployeeId,
                participant.ReviewerName));
        }

        var duplicates = assignments
            .GroupBy(item => new { item.RoundId, item.ParticipantEmployeeId, item.Kind })
            .Any(group => group.Count() > 1);
        if (duplicates)
            throw new DomainRuleViolationException("A round can contain only one assignment per participant and kind.");

        return assignments;
    }

    private static EvaluationAssignment Create(
        EvaluationRound round,
        EvaluationRoundParticipant participant,
        EvaluationAssignmentKind kind,
        Guid assigneeEmployeeId,
        string assigneeName)
    {
        if (assigneeEmployeeId == Guid.Empty)
            throw new DomainRuleViolationException("An evaluation assignment requires an assignee.");

        return new EvaluationAssignment
        {
            Id = Guid.NewGuid(),
            TenantId = round.TenantId,
            RoundId = round.Id,
            RoundParticipantId = participant.Id,
            ParticipantEmployeeId = participant.EmployeeId,
            ParticipantName = participant.FullName,
            Kind = kind,
            AssigneeEmployeeId = assigneeEmployeeId,
            AssigneeName = string.IsNullOrWhiteSpace(assigneeName) ? "(unknown)" : assigneeName.Trim(),
            ScaleSnapshotId = round.ScaleSnapshot!.Id,
            TemplateSnapshotId = round.TemplateSnapshot!.Id,
            ObjectivePlanSnapshotId = participant.ObjectivePlanSnapshotId,
            Status = EvaluationAssignmentStatus.NotStarted
        };
    }
}
