using EY.HRPlatform.Performance.Domain.Enums;
using EY.HRPlatform.Performance.Domain.Events;
using EY.HRPlatform.Performance.Exceptions;
using EY.HRPlatform.SharedKernel.Domain;
using EY.HRPlatform.SharedKernel.Multitenancy;

namespace EY.HRPlatform.Performance.Domain.Entities;

/// <summary>
/// A frozen participant-to-assignee relationship generated by one round launch, and the
/// unit of assessment work, status, and concurrency. Owns the author's responses and — on
/// the manager assignment — the finalized outcome. Every transition is guarded server-side
/// against the frozen launch snapshot; the aggregate never resolves live configuration.
/// </summary>
public sealed class EvaluationAssignment : AggregateRoot, ITenantEntity
{
    public const int DiscussionSummaryMaxLength = 4000;
    public const int AcknowledgementCommentMaxLength = 1000;
    public const int ReopenReasonMaxLength = 500;

    private readonly List<EvaluationObjectiveRating> _objectiveRatings = new();
    private readonly List<EvaluationSkillRating> _skillRatings = new();
    private readonly List<EvaluationQuestionAnswer> _questionAnswers = new();

    private EvaluationAssignment() { }

    public Guid TenantId { get; private set; }
    public Guid RoundId { get; private set; }
    public Guid RoundParticipantId { get; private set; }
    public Guid ParticipantEmployeeId { get; private set; }
    public string ParticipantName { get; private set; } = string.Empty;
    public EvaluationAssignmentKind Kind { get; private set; }
    public Guid AssigneeEmployeeId { get; private set; }
    public string AssigneeName { get; private set; } = string.Empty;
    public Guid ScaleSnapshotId { get; private set; }
    public Guid TemplateSnapshotId { get; private set; }
    public Guid? ObjectivePlanSnapshotId { get; private set; }
    public Guid? SkillSnapshotId { get; private set; }
    public EvaluationAssignmentStatus Status { get; private set; }
    public DateTime? SubmittedAt { get; private set; }
    public uint Version { get; private set; }

    // Manager-assignment-only outcome (nullable until finalization / acknowledgement).
    public int? OverallObjectivesRatingOrdinal { get; private set; }
    public int? OverallSkillsRatingOrdinal { get; private set; }
    public string? DiscussionSummary { get; private set; }
    public decimal? FinalScore { get; private set; }
    public int? FinalRatingOrdinal { get; private set; }
    public DateTime? FinalizedAt { get; private set; }
    public DateTime? AcknowledgedAt { get; private set; }
    public string? AcknowledgementComment { get; private set; }

    public IReadOnlyCollection<EvaluationObjectiveRating> ObjectiveRatings => _objectiveRatings.AsReadOnly();
    public IReadOnlyCollection<EvaluationSkillRating> SkillRatings => _skillRatings.AsReadOnly();
    public IReadOnlyCollection<EvaluationQuestionAnswer> QuestionAnswers => _questionAnswers.AsReadOnly();

    internal static IReadOnlyList<EvaluationAssignment> Generate(
        EvaluationRound round,
        IReadOnlyCollection<EvaluationRoundParticipant> participants)
    {
        if (round.Status != EvaluationRoundStatus.Launched ||
            round.ScaleSnapshot is null ||
            round.TemplateSnapshot is null)
        {
            throw new DomainRuleViolationException("Assignments can only be generated from a launched round snapshot.");
        }

        var assignments = new List<EvaluationAssignment>(
            participants.Count * (round.AssessmentModel == EvaluationAssessmentModel.SelfAndManager ? 2 : 1));

        foreach (var participant in participants)
        {
            if (participant.RoundId != round.Id || participant.TenantId != round.TenantId)
                throw new DomainRuleViolationException("Assignment participants must belong to the launched round.");

            if (round.AssessmentModel == EvaluationAssessmentModel.SelfAndManager)
            {
                assignments.Add(Create(
                    round,
                    participant,
                    EvaluationAssignmentKind.SelfAssessment,
                    participant.EmployeeId,
                    participant.FullName));
            }

            assignments.Add(Create(
                round,
                participant,
                EvaluationAssignmentKind.ManagerAssessment,
                participant.ReviewerEmployeeId,
                participant.ReviewerName));
        }

        var duplicates = assignments
            .GroupBy(item => new { item.RoundId, item.ParticipantEmployeeId, item.Kind })
            .Any(group => group.Count() > 1);
        if (duplicates)
            throw new DomainRuleViolationException("A round can contain only one assignment per participant and kind.");

        return assignments;
    }

    private static EvaluationAssignment Create(
        EvaluationRound round,
        EvaluationRoundParticipant participant,
        EvaluationAssignmentKind kind,
        Guid assigneeEmployeeId,
        string assigneeName)
    {
        if (assigneeEmployeeId == Guid.Empty)
            throw new DomainRuleViolationException("An evaluation assignment requires an assignee.");

        return new EvaluationAssignment
        {
            Id = Guid.NewGuid(),
            TenantId = round.TenantId,
            RoundId = round.Id,
            RoundParticipantId = participant.Id,
            ParticipantEmployeeId = participant.EmployeeId,
            ParticipantName = participant.FullName,
            Kind = kind,
            AssigneeEmployeeId = assigneeEmployeeId,
            AssigneeName = string.IsNullOrWhiteSpace(assigneeName) ? "(unknown)" : assigneeName.Trim(),
            ScaleSnapshotId = round.ScaleSnapshot!.Id,
            TemplateSnapshotId = round.TemplateSnapshot!.Id,
            ObjectivePlanSnapshotId = participant.ObjectivePlanSnapshotId,
            SkillSnapshotId = round.SkillSnapshot?.Id,
            Status = EvaluationAssignmentStatus.NotStarted
        };
    }

    /// <summary>
    /// Idempotent upsert of this assignment's responses against the frozen snapshot.
    /// Moves <c>NotStarted → InProgress</c> on first save. Rejected once a self-assessment
    /// is submitted or either assignment is finalized; a submitted manager assessment stays editable.
    /// </summary>
    public void SaveDraft(EvaluationAssessmentDraftInput input, EvaluationAssessmentSnapshot snapshot, DateTime now)
    {
        ArgumentNullException.ThrowIfNull(input);
        ArgumentNullException.ThrowIfNull(snapshot);
        EnsureAuthorable();

        foreach (var rating in input.ObjectiveRatings)
            UpsertObjectiveRating(rating, snapshot);
        foreach (var rating in input.SkillRatings)
            UpsertSkillRating(rating, snapshot);
        foreach (var answer in input.QuestionAnswers)
            UpsertQuestionAnswer(answer, snapshot);

        if (Status == EvaluationAssignmentStatus.NotStarted)
            Status = EvaluationAssignmentStatus.InProgress;
        UpdatedAt = NormalizeUtc(now);
    }

    /// <summary>
    /// Submits the assessment after server-side completeness validation. Self-assessments
    /// become immutable and notify the reviewer; a manager assessment stays editable until
    /// finalization. Concurrency-guarded by <see cref="Version"/>.
    /// </summary>
    public void Submit(EvaluationAssessmentSnapshot snapshot, DateTime now)
    {
        ArgumentNullException.ThrowIfNull(snapshot);
        EnsureAuthorable();
        if (Status != EvaluationAssignmentStatus.InProgress)
            throw new DomainRuleViolationException("An assessment must be in progress before it can be submitted.");

        var incomplete = CollectIncompleteItems(snapshot);
        if (incomplete.Count > 0)
            throw new EvaluationAssessmentIncompleteException(incomplete);

        Status = EvaluationAssignmentStatus.Submitted;
        SubmittedAt = NormalizeUtc(now);
        UpdatedAt = SubmittedAt;

        if (Kind == EvaluationAssignmentKind.SelfAssessment)
            AddDomainEvent(new EvaluationSelfAssessmentSubmittedEvent(
                TenantId, RoundId, Id, ParticipantEmployeeId, ParticipantName, AssigneeEmployeeId, AssigneeName));
    }

    /// <summary>
    /// Reopens a submitted self-assessment to <c>InProgress</c> with a required reason,
    /// preserving the entered content. Governed to before finalization; notifies the employee.
    /// </summary>
    public void ReopenSelf(string reason, DateTime now)
    {
        if (Kind != EvaluationAssignmentKind.SelfAssessment)
            throw new DomainRuleViolationException("Only a self-assessment can be reopened.");
        if (Status == EvaluationAssignmentStatus.Finalized)
            throw new DomainRuleViolationException("A finalized evaluation cannot be reopened.");
        if (Status != EvaluationAssignmentStatus.Submitted)
            throw new DomainRuleViolationException("Only a submitted self-assessment can be reopened.");

        var normalizedReason = NormalizeRequiredText(reason, ReopenReasonMaxLength, "A reopen reason is required.");

        Status = EvaluationAssignmentStatus.InProgress;
        SubmittedAt = null;
        UpdatedAt = NormalizeUtc(now);
        AddDomainEvent(new EvaluationSelfAssessmentReopenedEvent(
            TenantId, RoundId, Id, ParticipantEmployeeId, ParticipantName, normalizedReason));
    }

    /// <summary>
    /// Records the manager area ratings + discussion summary, computes the weighted result,
    /// and transitions the manager assignment (and the self assignment, when present) to
    /// <c>Finalized</c>. Available only from a submitted manager assessment.
    /// </summary>
    public void Finalize(
        EvaluationAssignment? selfAssignment,
        EvaluationFinalizationInput input,
        int objectivesWeightPercent,
        int skillsWeightPercent,
        int scaleLevelCount,
        DateTime now)
    {
        ArgumentNullException.ThrowIfNull(input);
        if (Kind != EvaluationAssignmentKind.ManagerAssessment)
            throw new DomainRuleViolationException("Only the manager assessment can be finalized.");
        if (Status == EvaluationAssignmentStatus.Finalized)
            throw new DomainRuleViolationException("The evaluation is already finalized.");
        if (Status != EvaluationAssignmentStatus.Submitted)
            throw new DomainRuleViolationException("The manager assessment must be submitted before finalization.");
        if (objectivesWeightPercent is < 0 or > 100 || skillsWeightPercent is < 0 or > 100 ||
            objectivesWeightPercent + skillsWeightPercent != 100)
        {
            throw new DomainRuleViolationException("Finalization weights must each be 0–100 and sum to 100.");
        }
        if (scaleLevelCount < 1)
            throw new DomainRuleViolationException("The performance scale must have at least one level.");

        if (selfAssignment is not null &&
            (selfAssignment.Kind != EvaluationAssignmentKind.SelfAssessment ||
             selfAssignment.TenantId != TenantId ||
             selfAssignment.RoundId != RoundId ||
             selfAssignment.ParticipantEmployeeId != ParticipantEmployeeId))
        {
            throw new DomainRuleViolationException("The self assignment must belong to the same participant and round.");
        }
        if (selfAssignment is { Status: EvaluationAssignmentStatus.Finalized })
            throw new DomainRuleViolationException("The self assignment is already finalized.");

        var summary = NormalizeRequiredText(
            input.DiscussionSummary, DiscussionSummaryMaxLength, "A discussion summary is required to finalize.");

        int? objectivesRating = objectivesWeightPercent > 0
            ? RequireScaleOrdinal(input.OverallObjectivesRatingOrdinal, scaleLevelCount, "objectives")
            : null;
        int? skillsRating = skillsWeightPercent > 0
            ? RequireScaleOrdinal(input.OverallSkillsRatingOrdinal, scaleLevelCount, "skills")
            : null;

        var weighted =
            ((objectivesRating ?? 0) * objectivesWeightPercent + (skillsRating ?? 0) * skillsWeightPercent) / 100m;
        var finalScore = Math.Round(weighted, 1, MidpointRounding.AwayFromZero);
        var finalOrdinal = Math.Clamp(
            (int)Math.Round(finalScore, 0, MidpointRounding.AwayFromZero), 1, scaleLevelCount);

        OverallObjectivesRatingOrdinal = objectivesRating;
        OverallSkillsRatingOrdinal = skillsRating;
        DiscussionSummary = summary;
        FinalScore = finalScore;
        FinalRatingOrdinal = finalOrdinal;
        FinalizedAt = NormalizeUtc(now);
        Status = EvaluationAssignmentStatus.Finalized;
        UpdatedAt = FinalizedAt;

        selfAssignment?.MarkFinalized(FinalizedAt.Value);

        AddDomainEvent(new EvaluationFinalizedEvent(
            TenantId, RoundId, Id, ParticipantEmployeeId, ParticipantName,
            AssigneeEmployeeId, AssigneeName, finalScore, finalOrdinal));
    }

    /// <summary>
    /// Records the employee's one-shot acknowledgement of the finalized evaluation on the
    /// manager assignment that carries the result. Immutable once set; notifies the reviewer.
    /// </summary>
    public void Acknowledge(string? comment, DateTime now)
    {
        if (Kind != EvaluationAssignmentKind.ManagerAssessment)
            throw new DomainRuleViolationException("Acknowledgement is recorded on the finalized evaluation.");
        if (Status != EvaluationAssignmentStatus.Finalized)
            throw new DomainRuleViolationException("Only a finalized evaluation can be acknowledged.");
        if (AcknowledgedAt.HasValue)
            throw new DomainRuleViolationException("This evaluation has already been acknowledged.");

        AcknowledgementComment = NormalizeOptionalText(comment, AcknowledgementCommentMaxLength);
        AcknowledgedAt = NormalizeUtc(now);
        UpdatedAt = AcknowledgedAt;
        AddDomainEvent(new EvaluationAcknowledgedEvent(
            TenantId, RoundId, Id, ParticipantEmployeeId, ParticipantName, AssigneeEmployeeId, AssigneeName));
    }

    /// <summary>
    /// Moves outstanding manager work to another reviewer without changing the assignment or any
    /// responses already entered. Finalized work is terminal and cannot be reassigned.
    /// </summary>
    public void ReassignReviewer(Guid reviewerEmployeeId, string reviewerName, DateTime now)
    {
        if (Kind != EvaluationAssignmentKind.ManagerAssessment)
            throw new DomainRuleViolationException("Only a manager assessment can be reassigned.");
        if (Status == EvaluationAssignmentStatus.Finalized)
            throw new DomainRuleViolationException("A finalized evaluation cannot be reassigned.");
        if (reviewerEmployeeId == Guid.Empty)
            throw new DomainRuleViolationException("A reassigned reviewer is required.");
        if (reviewerEmployeeId == ParticipantEmployeeId)
            throw new DomainRuleViolationException("A participant cannot review themselves.");
        if (string.IsNullOrWhiteSpace(reviewerName))
            throw new DomainRuleViolationException("A reassigned reviewer name is required.");

        AssigneeEmployeeId = reviewerEmployeeId;
        AssigneeName = reviewerName.Trim();
        UpdatedAt = NormalizeUtc(now);
    }

    private void MarkFinalized(DateTime finalizedAt)
    {
        Status = EvaluationAssignmentStatus.Finalized;
        FinalizedAt = finalizedAt;
        UpdatedAt = finalizedAt;
    }

    private void EnsureAuthorable()
    {
        if (Status == EvaluationAssignmentStatus.Finalized)
            throw new DomainRuleViolationException("A finalized evaluation is immutable.");
        if (Kind == EvaluationAssignmentKind.SelfAssessment && Status == EvaluationAssignmentStatus.Submitted)
            throw new DomainRuleViolationException("A submitted self-assessment is immutable.");
    }

    private void UpsertObjectiveRating(EvaluationObjectiveRatingInput input, EvaluationAssessmentSnapshot snapshot)
    {
        if (!snapshot.IncludesObjectives || !snapshot.ObjectiveSnapshotIds.Contains(input.ObjectiveSnapshotId))
            throw new DomainRuleViolationException("The objective does not belong to this assignment's frozen snapshot.");
        if (input.RatingOrdinal is int ordinal && !snapshot.PerformanceScaleOrdinals.Contains(ordinal))
            throw new DomainRuleViolationException("The objective rating must be on the frozen performance scale.");

        var comment = NormalizeOptionalText(input.Comment, EvaluationObjectiveRating.CommentMaxLength);
        var existing = _objectiveRatings.SingleOrDefault(item => item.ObjectiveSnapshotId == input.ObjectiveSnapshotId);
        if (existing is null)
            _objectiveRatings.Add(EvaluationObjectiveRating.Create(
                TenantId, Id, input.ObjectiveSnapshotId, input.RatingOrdinal, comment));
        else
            existing.Update(input.RatingOrdinal, comment);
    }

    private void UpsertSkillRating(EvaluationSkillRatingInput input, EvaluationAssessmentSnapshot snapshot)
    {
        if (!snapshot.IncludesSkills || !snapshot.SkillItemIds.Contains(input.SkillSnapshotItemId))
            throw new DomainRuleViolationException("The skill item does not belong to this assignment's frozen snapshot.");
        if (input.ProficiencyOrdinal is int ordinal && !snapshot.ProficiencyScaleOrdinals.Contains(ordinal))
            throw new DomainRuleViolationException("The skill rating must be on the frozen proficiency scale.");

        var comment = NormalizeOptionalText(input.Comment, EvaluationSkillRating.CommentMaxLength);
        var existing = _skillRatings.SingleOrDefault(item => item.SkillSnapshotItemId == input.SkillSnapshotItemId);
        if (existing is null)
            _skillRatings.Add(EvaluationSkillRating.Create(
                TenantId, Id, input.SkillSnapshotItemId, input.ProficiencyOrdinal, comment));
        else
            existing.Update(input.ProficiencyOrdinal, comment);
    }

    private void UpsertQuestionAnswer(EvaluationQuestionAnswerInput input, EvaluationAssessmentSnapshot snapshot)
    {
        var question = snapshot.Questions.SingleOrDefault(item => item.Id == input.QuestionSnapshotId)
            ?? throw new DomainRuleViolationException("The question does not belong to this assignment's frozen snapshot.");
        if (!IsQuestionForThisAssignment(question.TargetRater))
            throw new DomainRuleViolationException("The question is not targeted at this rater.");

        string? textAnswer = null;
        int? ratingOrdinal = null;
        var isNotApplicable = false;
        string? notApplicableReason = null;

        if (input.IsNotApplicable)
        {
            if (!question.AllowNotApplicable)
                throw new DomainRuleViolationException("This question does not allow a not-applicable answer.");
            isNotApplicable = true;
            notApplicableReason = NormalizeOptionalText(
                input.NotApplicableReason, EvaluationQuestionAnswer.NotApplicableReasonMaxLength);
            if (question.IsRequired && notApplicableReason is null)
                throw new DomainRuleViolationException("A reason is required to mark a required question not applicable.");
        }
        else if (question.Type == EvaluationQuestionType.Text)
        {
            textAnswer = NormalizeOptionalText(input.TextAnswer, EvaluationQuestionAnswer.TextAnswerMaxLength);
        }
        else
        {
            if (input.RatingOrdinal is int ordinal && !snapshot.PerformanceScaleOrdinals.Contains(ordinal))
                throw new DomainRuleViolationException("The question rating must be on the frozen performance scale.");
            ratingOrdinal = input.RatingOrdinal;
        }

        var existing = _questionAnswers.SingleOrDefault(item => item.QuestionSnapshotId == input.QuestionSnapshotId);
        if (existing is null)
            _questionAnswers.Add(EvaluationQuestionAnswer.Create(
                TenantId, Id, input.QuestionSnapshotId, textAnswer, ratingOrdinal, isNotApplicable, notApplicableReason));
        else
            existing.Update(textAnswer, ratingOrdinal, isNotApplicable, notApplicableReason);
    }

    private List<EvaluationAssessmentIncompleteItem> CollectIncompleteItems(EvaluationAssessmentSnapshot snapshot)
    {
        var incomplete = new List<EvaluationAssessmentIncompleteItem>();

        if (snapshot.IncludesObjectives)
        {
            foreach (var objectiveId in snapshot.ObjectiveSnapshotIds)
            {
                var rating = _objectiveRatings.SingleOrDefault(item => item.ObjectiveSnapshotId == objectiveId);
                if (rating?.RatingOrdinal is null)
                    incomplete.Add(new EvaluationAssessmentIncompleteItem(
                        EvaluationAssessmentItemKind.Objective, objectiveId));
            }
        }

        if (snapshot.IncludesSkills)
        {
            foreach (var skillItemId in snapshot.SkillItemIds)
            {
                var rating = _skillRatings.SingleOrDefault(item => item.SkillSnapshotItemId == skillItemId);
                if (rating?.ProficiencyOrdinal is null)
                    incomplete.Add(new EvaluationAssessmentIncompleteItem(
                        EvaluationAssessmentItemKind.Skill, skillItemId));
            }
        }

        foreach (var question in snapshot.Questions)
        {
            if (!question.IsRequired || !IsQuestionForThisAssignment(question.TargetRater))
                continue;
            var answer = _questionAnswers.SingleOrDefault(item => item.QuestionSnapshotId == question.Id);
            if (!IsQuestionAnswered(question, answer))
                incomplete.Add(new EvaluationAssessmentIncompleteItem(
                    EvaluationAssessmentItemKind.Question, question.Id));
        }

        return incomplete;
    }

    private static bool IsQuestionAnswered(EvaluationAssessmentQuestion question, EvaluationQuestionAnswer? answer)
    {
        if (answer is null)
            return false;
        if (answer.IsNotApplicable)
            return true;
        return question.Type == EvaluationQuestionType.Text
            ? !string.IsNullOrWhiteSpace(answer.TextAnswer)
            : answer.RatingOrdinal is not null;
    }

    private bool IsQuestionForThisAssignment(EvaluationTargetRater targetRater) => targetRater switch
    {
        EvaluationTargetRater.Both => true,
        EvaluationTargetRater.Self => Kind == EvaluationAssignmentKind.SelfAssessment,
        EvaluationTargetRater.Manager => Kind == EvaluationAssignmentKind.ManagerAssessment,
        _ => false
    };

    private static int RequireScaleOrdinal(int? value, int scaleLevelCount, string area)
    {
        if (value is not int ordinal)
            throw new DomainRuleViolationException($"An overall {area} rating is required to finalize.");
        if (ordinal < 1 || ordinal > scaleLevelCount)
            throw new DomainRuleViolationException($"The overall {area} rating must be on the frozen performance scale.");
        return ordinal;
    }

    private static string NormalizeRequiredText(string value, int maxLength, string missingMessage)
    {
        if (string.IsNullOrWhiteSpace(value))
            throw new DomainRuleViolationException(missingMessage);
        var trimmed = value.Trim();
        if (trimmed.Length > maxLength)
            throw new DomainRuleViolationException($"The text cannot exceed {maxLength} characters.");
        return trimmed;
    }

    private static string? NormalizeOptionalText(string? value, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;
        var trimmed = value.Trim();
        if (trimmed.Length > maxLength)
            throw new DomainRuleViolationException($"The text cannot exceed {maxLength} characters.");
        return trimmed;
    }

    private static DateTime NormalizeUtc(DateTime value) => value.Kind switch
    {
        DateTimeKind.Utc => value,
        DateTimeKind.Local => value.ToUniversalTime(),
        _ => DateTime.SpecifyKind(value, DateTimeKind.Utc)
    };
}
