import type { Test, Question } from "@/types";

export const MOCK_TESTS: Test[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer Assessment",
    description: "Comprehensive React & TypeScript evaluation for senior roles.",
    discipline: "Engineering",
    role: "Senior Frontend Engineer",
    questionTypes: ["Coding", "Multiple Choice"],
    questionCount: 12,
    candidateCount: 48,
    status: "Active",
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    title: "Product Designer Skills Test",
    description: "UX thinking, Figma proficiency and design systems knowledge.",
    discipline: "Design",
    role: "Product Designer",
    questionTypes: ["Design", "Essay"],
    questionCount: 8,
    candidateCount: 32,
    status: "Active",
    createdAt: "2026-01-20",
  },
  {
    id: "3",
    title: "Data Analyst SQL Challenge",
    description: "Advanced SQL queries, data modeling and analysis tasks.",
    discipline: "Data",
    role: "Data Analyst",
    questionTypes: ["SQL", "Multiple Choice"],
    questionCount: 15,
    candidateCount: 61,
    status: "Active",
    createdAt: "2026-01-22",
  },
  {
    id: "4",
    title: "Backend Engineer Take-Home",
    description: "System design, API architecture and coding challenges.",
    discipline: "Engineering",
    role: "Backend Engineer",
    questionTypes: ["Coding", "Essay"],
    questionCount: 10,
    candidateCount: 27,
    status: "Draft",
    createdAt: "2026-02-01",
  },
  {
    id: "5",
    title: "Marketing Analytics Assessment",
    description: "Campaign analysis, KPI interpretation and strategy questions.",
    discipline: "Marketing",
    role: "Marketing Analyst",
    questionTypes: ["Multiple Choice", "Essay", "Excel"],
    questionCount: 20,
    candidateCount: 14,
    status: "Active",
    createdAt: "2026-02-05",
  },
  {
    id: "6",
    title: "Financial Modeling Test",
    description: "Excel-based financial modeling and valuation exercises.",
    discipline: "Finance",
    role: "Financial Analyst",
    questionTypes: ["Excel", "Multiple Choice"],
    questionCount: 9,
    candidateCount: 19,
    status: "Archived",
    createdAt: "2025-11-10",
  },
  {
    id: "7",
    title: "DevOps Engineering Screening",
    description: "CI/CD pipelines, container orchestration and cloud infra.",
    discipline: "Engineering",
    role: "DevOps Engineer",
    questionTypes: ["Coding", "Multiple Choice", "True/False"],
    questionCount: 18,
    candidateCount: 33,
    status: "Active",
    createdAt: "2026-02-10",
  },
  {
    id: "8",
    title: "Product Manager Case Study",
    description: "Product strategy, prioritisation and stakeholder management.",
    discipline: "Product",
    role: "Product Manager",
    questionTypes: ["Case Study", "Essay"],
    questionCount: 6,
    candidateCount: 55,
    status: "Active",
    createdAt: "2026-02-12",
  },
  {
    id: "9",
    title: "Operations Analyst Evaluation",
    description: "Process optimisation, logistics and data-driven operations.",
    discipline: "Operations",
    role: "Operations Analyst",
    questionTypes: ["Multiple Choice", "True/False"],
    questionCount: 25,
    candidateCount: 11,
    status: "Draft",
    createdAt: "2026-02-18",
  },
  {
    id: "10",
    title: "Full Stack Developer Comprehensive",
    description: "End-to-end web development covering frontend and backend.",
    discipline: "Engineering",
    role: "Full Stack Developer",
    questionTypes: ["Coding", "SQL", "Multiple Choice"],
    questionCount: 22,
    candidateCount: 40,
    status: "Active",
    createdAt: "2026-02-20",
  },
  {
    id: "11",
    title: "UX Research Assessment",
    description: "Research methodologies, synthesis and presentation skills.",
    discipline: "Design",
    role: "UX Researcher",
    questionTypes: ["Essay", "Case Study"],
    questionCount: 7,
    candidateCount: 22,
    status: "Archived",
    createdAt: "2025-12-05",
  },
  {
    id: "12",
    title: "Data Science Screening Test",
    description: "Statistics, ML fundamentals and Python data manipulation.",
    discipline: "Data",
    role: "Data Scientist",
    questionTypes: ["Coding", "Multiple Choice", "Essay"],
    questionCount: 14,
    candidateCount: 36,
    status: "Active",
    createdAt: "2026-02-25",
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: "q1",
    title: "Implement a debounce function",
    description: "Write a debounce utility in TypeScript with configurable delay and immediate execution option.",
    type: "Coding",
    difficulty: "Medium",
    gradingMethod: "Auto-graded",
    duration: 20,
    points: 10,
    tags: ["TypeScript", "Utilities", "Performance"],
    usageCount: 124,
  },
  {
    id: "q2",
    title: "SQL Window Functions",
    description: "Using the provided sales dataset, calculate rolling 7-day averages using window functions.",
    type: "SQL",
    difficulty: "Hard",
    gradingMethod: "Auto-graded",
    duration: 25,
    points: 15,
    tags: ["SQL", "Analytics", "Window Functions"],
    usageCount: 89,
  },
  {
    id: "q3",
    title: "React hooks best practices",
    description: "Identify and fix common mistakes in the provided React component that uses hooks incorrectly.",
    type: "Multiple Choice",
    difficulty: "Easy",
    gradingMethod: "Auto-graded",
    duration: 10,
    points: 5,
    tags: ["React", "Hooks", "Best Practices"],
    usageCount: 210,
  },
  {
    id: "q4",
    title: "System design: URL shortener",
    description: "Design a scalable URL shortener service. Consider high availability, caching, and analytics.",
    type: "Essay",
    difficulty: "Expert",
    gradingMethod: "Manual review",
    duration: 45,
    points: 25,
    tags: ["System Design", "Scalability", "Architecture"],
    usageCount: 67,
  },
  {
    id: "q5",
    title: "Product prioritisation framework",
    description: "Given a backlog of 10 features with user impact and effort estimates, build a prioritisation case.",
    type: "Case Study",
    difficulty: "Hard",
    gradingMethod: "Manual review",
    duration: 60,
    points: 30,
    tags: ["Product", "Prioritisation", "Strategy"],
    usageCount: 45,
  },
  {
    id: "q6",
    title: "Excel VLOOKUP and pivot tables",
    description: "Use VLOOKUP and pivot tables to consolidate and summarise the provided quarterly sales data.",
    type: "Excel",
    difficulty: "Medium",
    gradingMethod: "Hybrid",
    duration: 30,
    points: 20,
    tags: ["Excel", "Data Analysis", "Finance"],
    usageCount: 78,
  },
  {
    id: "q7",
    title: "Binary search tree operations",
    description: "Implement insert, delete and in-order traversal for a BST. Include time complexity analysis.",
    type: "Coding",
    difficulty: "Hard",
    gradingMethod: "Auto-graded",
    duration: 35,
    points: 20,
    tags: ["Data Structures", "Algorithms", "Trees"],
    usageCount: 156,
  },
  {
    id: "q8",
    title: "CSS layout true/false quiz",
    description: "10 true/false statements about CSS Flexbox and Grid behaviour and browser rendering.",
    type: "True/False",
    difficulty: "Easy",
    gradingMethod: "Auto-graded",
    duration: 8,
    points: 5,
    tags: ["CSS", "Layout", "Frontend"],
    usageCount: 302,
  },
  {
    id: "q9",
    title: "Design system component audit",
    description: "Review the provided Figma file and identify inconsistencies against the design system tokens.",
    type: "Design",
    difficulty: "Medium",
    gradingMethod: "Manual review",
    duration: 40,
    points: 20,
    tags: ["Design Systems", "Figma", "Audit"],
    usageCount: 34,
  },
  {
    id: "q10",
    title: "Normalise a database schema",
    description: "Given a denormalised e-commerce schema, apply 3NF normalisation and justify each step.",
    type: "SQL",
    difficulty: "Expert",
    gradingMethod: "Hybrid",
    duration: 50,
    points: 30,
    tags: ["Database Design", "Normalisation", "SQL"],
    usageCount: 72,
  },
  {
    id: "q11",
    title: "REST API error handling",
    description: "Identify the best HTTP status codes and error response shapes for the given API scenarios.",
    type: "Multiple Choice",
    difficulty: "Medium",
    gradingMethod: "Auto-graded",
    duration: 12,
    points: 8,
    tags: ["API Design", "REST", "Backend"],
    usageCount: 188,
  },
  {
    id: "q12",
    title: "Marketing funnel analysis essay",
    description: "Analyse the provided campaign data and write a strategic recommendation to improve conversion.",
    type: "Essay",
    difficulty: "Medium",
    gradingMethod: "Manual review",
    duration: 40,
    points: 20,
    tags: ["Marketing", "Analytics", "Strategy"],
    usageCount: 28,
  },
  {
    id: "q13",
    title: "Async JavaScript patterns",
    description: "Refactor the callback-based code to use async/await and handle all edge-case errors.",
    type: "Coding",
    difficulty: "Medium",
    gradingMethod: "Auto-graded",
    duration: 25,
    points: 12,
    tags: ["JavaScript", "Async", "Error Handling"],
    usageCount: 143,
  },
  {
    id: "q14",
    title: "Agile ceremonies true/false",
    description: "15 true/false questions about Scrum ceremonies, roles and artefacts.",
    type: "True/False",
    difficulty: "Easy",
    gradingMethod: "Auto-graded",
    duration: 10,
    points: 5,
    tags: ["Agile", "Scrum", "Process"],
    usageCount: 265,
  },
  {
    id: "q15",
    title: "Financial ratio analysis",
    description: "Calculate and interpret key financial ratios from the provided balance sheet and income statement.",
    type: "Excel",
    difficulty: "Hard",
    gradingMethod: "Hybrid",
    duration: 45,
    points: 25,
    tags: ["Finance", "Ratios", "Analysis"],
    usageCount: 51,
  },
  {
    id: "q16",
    title: "Accessibility audit case study",
    description: "Evaluate the provided web page against WCAG 2.1 AA criteria and produce a remediation plan.",
    type: "Case Study",
    difficulty: "Hard",
    gradingMethod: "Manual review",
    duration: 55,
    points: 30,
    tags: ["Accessibility", "WCAG", "Frontend"],
    usageCount: 29,
  },
  {
    id: "q17",
    title: "Python data wrangling",
    description: "Use pandas to clean, merge and aggregate the provided messy datasets into a summary report.",
    type: "Coding",
    difficulty: "Medium",
    gradingMethod: "Auto-graded",
    duration: 30,
    points: 15,
    tags: ["Python", "Pandas", "Data"],
    usageCount: 97,
  },
  {
    id: "q18",
    title: "UX heuristics evaluation",
    description: "Apply Nielsen's 10 heuristics to the provided app screenshots and score each violation.",
    type: "Design",
    difficulty: "Medium",
    gradingMethod: "Hybrid",
    duration: 35,
    points: 18,
    tags: ["UX", "Heuristics", "Evaluation"],
    usageCount: 41,
  },
  {
    id: "q19",
    title: "Cloud infrastructure MCQ",
    description: "20 multiple choice questions covering AWS, GCP and Azure core services and pricing models.",
    type: "Multiple Choice",
    difficulty: "Hard",
    gradingMethod: "Auto-graded",
    duration: 20,
    points: 10,
    tags: ["Cloud", "AWS", "Infrastructure"],
    usageCount: 134,
  },
  {
    id: "q20",
    title: "Operations process improvement essay",
    description: "Describe how you would apply lean principles to reduce waste in the described supply chain.",
    type: "Essay",
    difficulty: "Hard",
    gradingMethod: "Manual review",
    duration: 45,
    points: 25,
    tags: ["Operations", "Lean", "Process"],
    usageCount: 22,
  },
];

export async function getTests(): Promise<Test[]> {
  return MOCK_TESTS;
}

export async function getQuestions(): Promise<Question[]> {
  return MOCK_QUESTIONS;
}