// Single terminology source for the employee "My objectives" surface — product language only,
// no enum or lifecycle codes leak to the screen.

export const myObjectiveTerms = {
  listTitle: "My objectives",
  listDescription:
    "Choose an active performance campaign, shape your objective plan, and submit it for manager review.",
  accessTitle: "My objectives access required",
  emptyListTitle: "No campaign objective plan",
  emptyListDescription:
    "When you are included in a launched campaign, your personal plan will appear here.",
  draft: "Draft",
  submitted: "Submitted",
  changesRequested: "Changes requested",
  approved: "Approved",
  awaitingReview: "Awaiting manager review",
  approvedReadOnly: "Approved objective plan",
  changesRequestedTitle: "Changes requested",
  changesRequestedBy: (managerName: string, requestedAt: string | null) =>
    `Returned by ${managerName}${requestedAt ? ` · ${requestedAt}` : ""}`,
  yourManager: "Your manager",
  managerComment: (managerName: string) => `${managerName} comment`,
  noManagerComment: "No comment recorded.",
  scope: "References",
  fullPlanWithCount: (count: number) => `Full plan · ${count} objective${count === 1 ? "" : "s"}`,
  referencedObjectivesWithCount: (count: number) =>
    `${count} reference${count === 1 ? "" : "s"} · full plan`,
  updateAndResubmit: "Resubmit after edits",
  readyToResubmit: "Ready to resubmit",
  editsRequired: "Edits required",
  entryClosed: "Opens later",
  balanced: "Balanced",
  toAllocate: (value: number) => `${value}% to allocate`,
  over: (value: number) => `${value}% over`,
  count: (count: number, max: number) => `${count} of ${max} objectives`,
  addFirst: "Add your first objective",
  addObjective: "Add objective",
  objectivesHeading: "Objectives",
  complete: "Ready",
  needsDetail: "Missing details",
  missingPrefix: "Missing:",
  supports: "Supports",
  measure: "Measure",
  due: "Due",
  notSet: "Not set",
  readyToSubmit: "Ready to submit",
  planWeight: "Plan weight",
  nextStep: "Next",
  managerReview: "Manager review",
  submit: "Submit plan",
  resubmit: "Resubmit plan",
  submitConfirmTitle: "Submit this objective plan?",
  submitConfirmDescription:
    "Your plan becomes read-only and moves to your manager for review.",
  submitConfirm: "Submit plan",
  submitCancel: "Keep editing",
  reviewNote: "Read-only while your manager reviews it.",
  approvedNote: "Read-only. This approved plan is your planning baseline.",
  submittedLabel: "Submitted",
  managerLabel: "Manager",
  entryNotOpenTitle: "Objective planning isn't open yet",
  entryNotOpenDescription: (date: string) => `You can start building your plan on ${date}.`,
  deleteTitle: "Delete this objective?",
  deleteDescription: "It will be removed from your draft plan.",
  deleteConfirm: "Delete objective",
  deleteCancel: "Keep objective",
  saved: "Objective saved",
  deleted: "Objective deleted",
  submittedToast: "Objective plan submitted",
  conflict: "This plan changed in another place. We refreshed it — review and try again.",
} as const;

export const objectiveEditorTerms = {
  createTitle: "Add objective",
  editTitle: "Edit objective",
  titleLabel: "Objective",
  titlePlaceholder: "What will you accomplish this year?",
  alignmentLabel: "Supports",
  alignmentPlaceholder: "Choose what this drives",
  alignmentTeamGroup: "Your team's objectives",
  alignmentStrategyGroup: "Company strategy",
  weightLabel: "Weight",
  weightLeaves: (value: number) => `leaves ${value}%`,
  weightOver: (value: number) => `${value}% over budget`,
  deadlineLabel: "Target date",
  measurementLabel: "How it's measured",
  indicatorLabel: "Indicator",
  indicatorPlaceholder: "e.g. Net revenue",
  targetLabel: "Target",
  targetPlaceholder: "e.g. 1.2M",
  unitLabel: "Unit",
  unitPlaceholder: "e.g. TND",
  successLabel: "What good looks like",
  successPlaceholder: "Describe the outcome that means success",
  contextLabel: "Context",
  contextPlaceholder: "Optional detail for your manager",
  cancel: "Cancel",
  save: "Save objective",
  saving: "Saving…",
} as const;
