@EY.HRPlatform.CoreHR_HostAddress = http://localhost:5301

### Liveness probe
GET {{EY.HRPlatform.CoreHR_HostAddress}}/api/corehr/health/live
Accept: application/json

###

### Readiness probe
GET {{EY.HRPlatform.CoreHR_HostAddress}}/api/corehr/health/ready
Accept: application/json

###

### Prometheus metrics
GET {{EY.HRPlatform.CoreHR_HostAddress}}/api/corehr/metrics

###
