// <auto-generated />
using EY.HRPlatform.Performance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EY.HRPlatform.Performance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20260629160000_AddStarterTemplatesAndMigrateLegacy")]
    partial class AddStarterTemplatesAndMigrateLegacy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
