// <auto-generated />
using System;
using EY.HRPlatform.Performance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EY.HRPlatform.Performance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20260821052910_InitialPerformanceCycleAndGoals")]
    partial class InitialPerformanceCycleAndGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("performance")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Cycles.ActivationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConfirmedParticipantCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("EligibilityDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlanningDeadline")
                        .HasColumnType("date");

                    b.Property<string>("PopulationRuleJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RosterJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("StrategyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.ToTable("ActivationSnapshots", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Cycles.PerformanceCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActiveTenantSlot")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("PlanningDeadline")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTenantSlot")
                        .IsUnique()
                        .HasFilter("\"ActiveTenantSlot\" IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("PerformanceCycles", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.ContributionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.HasIndex("ObjectiveId", "ChildObjectiveId")
                        .IsUnique();

                    b.ToTable("ObjectiveContributionLinks", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountablePersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ContributionBaselineLockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgUnitName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("OwnershipScope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("ParentObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProgressSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("ParentObjectiveId");

                    b.HasIndex("TenantId");

                    b.ToTable("Objectives", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.ObjectiveDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("ObjectiveDecisions", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ByExplicitInclusion")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ManagerDisplayName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgUnitName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("CycleId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("Participants", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EligibilityDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CycleId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("PopulationDefinitions", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationExclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PopulationDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PopulationDefinitionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PopulationExclusions", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationInclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PopulationDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PopulationDefinitionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("PopulationInclusions", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationOrgUnitSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IncludeDescendants")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PopulationDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PopulationDefinitionId");

                    b.HasIndex("PopulationDefinitionId", "OrgUnitId")
                        .IsUnique();

                    b.ToTable("PopulationOrgUnitSelections", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Settings.CycleSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowStandaloneObjectives")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefaultMeasurementMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("PlanningDeadlineOffsetDays")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedObjectiveCountMax")
                        .HasColumnType("integer");

                    b.Property<int>("SuggestedObjectiveCountMin")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("CycleSettings", "performance");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Cycles.ActivationSnapshot", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Cycles.PerformanceCycle", null)
                        .WithOne("ActivationSnapshot")
                        .HasForeignKey("EY.HRPlatform.Performance.Domain.Cycles.ActivationSnapshot", "CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.ContributionLink", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Objectives.Objective", null)
                        .WithMany("ContributionLinks")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.Objective", b =>
                {
                    b.OwnsOne("EY.HRPlatform.Performance.Domain.Objectives.ObjectiveMeasurement", "Measurement", b1 =>
                        {
                            b1.Property<Guid>("ObjectiveId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Baseline")
                                .HasColumnType("numeric(18,4)");

                            b1.Property<string>("Direction")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)");

                            b1.Property<decimal?>("Target")
                                .HasColumnType("numeric(18,4)");

                            b1.Property<string>("Unit")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)");

                            b1.HasKey("ObjectiveId");

                            b1.ToTable("Objectives", "performance");

                            b1.WithOwner()
                                .HasForeignKey("ObjectiveId");

                            b1.OwnsMany("EY.HRPlatform.Performance.Domain.Objectives.ObjectiveMilestone", "Milestones", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("CreatedBy")
                                        .HasColumnType("text");

                                    b2.Property<DateOnly?>("DueDate")
                                        .HasColumnType("date");

                                    b2.Property<bool>("IsCompleted")
                                        .HasColumnType("boolean");

                                    b2.Property<Guid>("ObjectiveId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("TenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)");

                                    b2.Property<DateTime?>("UpdatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("UpdatedBy")
                                        .HasColumnType("text");

                                    b2.Property<decimal>("Weight")
                                        .HasColumnType("numeric(6,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ObjectiveId");

                                    b2.ToTable("ObjectiveMilestones", "performance");

                                    b2.WithOwner()
                                        .HasForeignKey("ObjectiveId");
                                });

                            b1.Navigation("Milestones");
                        });

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.ObjectiveDecision", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Objectives.Objective", null)
                        .WithMany("Decisions")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationExclusion", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Population.PopulationDefinition", null)
                        .WithMany("Exclusions")
                        .HasForeignKey("PopulationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationInclusion", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Population.PopulationDefinition", null)
                        .WithMany("Inclusions")
                        .HasForeignKey("PopulationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationOrgUnitSelection", b =>
                {
                    b.HasOne("EY.HRPlatform.Performance.Domain.Population.PopulationDefinition", null)
                        .WithMany("OrgUnitSelections")
                        .HasForeignKey("PopulationDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Cycles.PerformanceCycle", b =>
                {
                    b.Navigation("ActivationSnapshot");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Objectives.Objective", b =>
                {
                    b.Navigation("ContributionLinks");

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("EY.HRPlatform.Performance.Domain.Population.PopulationDefinition", b =>
                {
                    b.Navigation("Exclusions");

                    b.Navigation("Inclusions");

                    b.Navigation("OrgUnitSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
